# Generated by Django 2.0.4 on 2018-04-28 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20180428_0551'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='res_user',
        ),
    ]
